version: "3.8"
services:
    web:
        image: cecidimitrov/newapp-web
        deploy:
            replicas: 5
        ports:
            - 8080:80
        volumes:
            - home/vagrant/newapp/web:/var/www/html:ro"
        networks:
            - app-network
    db:
        image: cecidimitrov/newapp-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    app-network:

